from setuptools import setup, find_packages

setup(
    name="cissa",
    version="0.1.0",
    description="CISSA: Company Integrated Systematic Sustainability Analysis - Valuation methodology with portfolio optimization",
    author="RoZetta Technology",
    author_email="dev@rozettatechnology.com",
    url="https://github.com/rozettatechnology/cissa",
    packages=find_packages(),
    python_requires=">=3.14",
    install_requires=[
        "pandas==3.0.1",
        "psycopg2-binary==2.9.11",
        "sqlalchemy==2.0.46",
        "statsmodels==0.14.6",
        "matplotlib==3.10.8",
        "numpy==2.4.2",
        "scipy==1.17.0",
        "xlwings==0.33.20",
        "dash==4.0.0",
        "plotly==6.5.2",
        "openpyxl==3.1.5",
        "tqdm==4.67.3",
        "pytest==9.0.2",
        "boto3==1.42.53",
        "fastapi==0.104.1",
        "uvicorn[standard]==0.24.0",
        "pydantic==2.5.0",
        "pydantic-settings==2.1.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "Topic :: Office/Business :: Financial :: Investment",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.14",
    ],
)
